# Starts equivalent of 'external services' as much as we can. 
# If something is not dockerizable, you should refer to proper DEV instances.

version: '3.8'

# Simple short name to make logs shorter (default name is much longer as copied from folder name)
name: crd

services:
  postgres:
    build:
      context: service-postgres
      # specially prepared dockerfile to init database schemas per application
      # in the same way how the expect in local stack
      # and run initdb parts of all uservices
      dockerfile: Dockerfile.local
    environment:
      # some master user and password. Please do not use it in any microservice.
      # Instead, defined user / schema per each uservice.
      - POSTGRES_USER=devlocaldb
      - POSTGRES_PASSWORD=devlocaldb
    ports:
      - 5432:5432

  local-stack-java-sdk-build:
    image: local-stack-java-sdk
    build:
      context: service-localsdk
      dockerfile: Dockerfile.local

  uservice-trade-initdb:
    build:
      context: uservice-trade/
      dockerfile: ./initdb/Dockerfile.local
    environment:
      # well-known properties defined by init scripts of our postgresql
      - DATABASE_USERNAME=uservice_trade_role_name
      - DATABASE_PASSWORD=uservice_trade_role_password
      - DATABASE_SCHEMA=uservice_trade
      - DATABASE_JDBC=jdbc:postgresql://postgres:5432/devlocaldb
    volumes:
      # Map local maven repo to speed up build by avoiding downloading maven dependencies each time to new docker image
      - ~/.m2/:/.m2
      # Map local source files to allow run initdb module from sources
      - ./uservice-trade/:/uservice-trade-src
    depends_on:
      postgres:
        condition: service_started
      local-stack-java-sdk-build:
        condition: service_completed_successfully
  