resources:
  - repo: self

variables:
  # connection, defined manually in .
  # The connection used in pipeline allows to access to ACR projectname.azurecr.io
  dockerRegistryServiceConnection: "projectname-cr-dev"
  # name of the registry where the image is hosted on.
  # in Docker world, it is also part of image name (prefix)
  containerRegistry: "charlesriverdevunofficial.azurecr.io"
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      # We have to include all folders where source files are located
      - /uservice-deal/
      - /api/
      - /libs-java/
      - /uservice-webapi/

pr:
  branches:
    include:
      - main
  paths:
    include:
      # the same folders as for trigger
      - /uservice-deal/
      - /api/
      - /libs-java/
      - /uservice-webapi/

jobs:
  - job: CICD
    displayName: µService Deal CI/CD build
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - bash: |
          echo "##vso[task.setvariable variable=SEMVERSION]$(head -1 uservice-deal/.semversion)"
        displayName: Use version from local .semversion file

      - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          SonarCloud: 'Sonar Test'
          organization: blueaadvark
          scannerMode: Other
          extraProperties:
            #sonar.projectKey=932308e2aea612ffd10a63b8a43573cf553e4c4b
            sonar.projectKey=blueaadvark

      - task: DownloadSecureFile@1
        displayName: 'Download secure file'
        name: mvnSettings
        inputs:
          secureFile: '0688ab68-a2cc-4d09-9942-161e3d378426'

      - task: Maven@4
        displayName: 'API libs build and test'
        inputs:
          mavenOptions: $(MAVEN_OPTS)
          mavenPomFile: 'api/client-java/pom.xml'
          goals: 'install'
          javaHomeOption: JDKVersion
          jdkVersionOption: 1.17
          codeCoverageToolOption: JaCoCo
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          #  - use settings.xml stored in Azure secure file areas
          options: -B --no-transfer-progress -s $(mvnSettings.secureFilePath)
          checkStyleRunAnalysis: true # We use checkstyle in coding, so let's use it with Maven as well

      - task: Maven@4
        displayName: 'Shared libs build and test'
        inputs:
          mavenOptions: $(MAVEN_OPTS)
          mavenPomFile: 'libs-java/pom.xml'
          goals: 'install'
          javaHomeOption: JDKVersion
          jdkVersionOption: 1.17
          codeCoverageToolOption: JaCoCo
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          #  - use settings.xml stored in Azure secure file areas
          options: -B --no-transfer-progress -s $(mvnSettings.secureFilePath)
          checkStyleRunAnalysis: true # We use checkstyle in coding, so let's use it with Maven as well


                 
      - task: Maven@4
        displayName: 'µService Deal test and build'
        inputs:
          mavenOptions: $(MAVEN_OPTS)
          mavenPomFile: 'uservice-deal/pom.xml'
          goals: 'install'
          javaHomeOption: JDKVersion
          jdkVersionOption: 1.17
          codeCoverageToolOption: JaCoCo
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          #  - use semversion for generated backend
          #  - use settings.xml stored in Azure secure file areas
          options: -B --no-transfer-progress -DREVISION=$(SEMVERSION) -s $(mvnSettings.secureFilePath)
          checkStyleRunAnalysis: true # We use checkstyle in coding, so let's use it with Maven as well
          publishJUnitResults: true

      - task: Maven@4
        displayName: 'µService Webapi test and build'
        inputs:
          mavenOptions: $(MAVEN_OPTS)
          mavenPomFile: 'uservice-webapi/pom.xml'
          goals: 'install'
          javaHomeOption: JDKVersion
          jdkVersionOption: 1.17
          codeCoverageToolOption: JaCoCo
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          #  - use semversion for generated backend
          #  - use settings.xml stored in Azure secure file areas
          options: -B --no-transfer-progress -DREVISION=$(SEMVERSION) -s $(mvnSettings.secureFilePath)
          checkStyleRunAnalysis: true # We use checkstyle in coding, so let's use it with Maven as well
          publishJUnitResults: true
     
      - task: Maven@4
        displayName: Build µService Deal docker image
        inputs:
          mavenOptions: $(MAVEN_OPTS)
          mavenPomFile: 'uservice-deal/pom.xml'
          goals: 'jib:buildTar'
          javaHomeOption: JDKVersion
          jdkVersionOption: 1.17
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          options: -B --no-transfer-progress -Djib.to.tags=latest,$(SEMVERSION)      
          
      - task: Maven@4
        displayName: Build µService Webapid ocker image
        inputs:
          mavenOptions: $(MAVEN_OPTS)
          mavenPomFile: 'uservice-webapi/pom.xml'
          goals: 'jib:buildTar'
          javaHomeOption: JDKVersion
          jdkVersionOption: 1.17
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          options: -B --no-transfer-progress -Djib.to.tags=latest,$(SEMVERSION)      
          

      
